name: Test-GithubActions-Job

on:
  push:
    branches:
    - main

env:
  NAME: "User-1"  

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print MSG
      run: echo "HeLLo ${NAME}"
