name: Test-GithubActions-Job

on:
  push:
    branches:
    - main

env:
  NAME: "User-1"  
  REGION: "ap-south"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print MSG
      run: |
        echo "HeLLo ${NAME}"
        echo "Region - ${{env.REGION}}"
