name: Test-GithubActions-Job

on:
  push:
    branches:
    - main

env:
  NAME: "User-1"  
  REGION: "ap-south"

jobs:
  test-job:
    env:
      STAGE: "dev"
    runs-on: ubuntu-latest
    steps:
    - name: Print MSG
      env:
        APP_VERSION: "v-1"
      run: |
        echo "HeLLo ${NAME}"
        echo "Region - ${{env.REGION}}"
        echo "Stage - ${{env.STAGE}}"
        echo "AppVersion - ${{env.APP_VERSION}}"
        
